// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhzgytqcgcf2uSMtR5ioM5bvo8LKK9Kbk',
    appId: '1:647133707927:web:b115560a3e4a5611f3f3d2',
    messagingSenderId: '647133707927',
    projectId: 'study-app-6ac16',
    authDomain: 'study-app-6ac16.firebaseapp.com',
    storageBucket: 'study-app-6ac16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzu2DD6UevO4NNIoFhEienrCR9D2Ns6ks',
    appId: '1:647133707927:android:c8aade4007ad38c8f3f3d2',
    messagingSenderId: '647133707927',
    projectId: 'study-app-6ac16',
    storageBucket: 'study-app-6ac16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgoDVeGRVvSB4mK8cKRTTF4guc3GhBPUQ',
    appId: '1:647133707927:ios:fe21998d0a25e45cf3f3d2',
    messagingSenderId: '647133707927',
    projectId: 'study-app-6ac16',
    storageBucket: 'study-app-6ac16.appspot.com',
    iosClientId: '647133707927-666645te3fd7dc214o3q3u75v44kir9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgoDVeGRVvSB4mK8cKRTTF4guc3GhBPUQ',
    appId: '1:647133707927:ios:fe21998d0a25e45cf3f3d2',
    messagingSenderId: '647133707927',
    projectId: 'study-app-6ac16',
    storageBucket: 'study-app-6ac16.appspot.com',
    iosClientId: '647133707927-666645te3fd7dc214o3q3u75v44kir9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFireBase',
  );
}
